apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mc-pos

# Resources to deploy
resources:
  - namespace.yaml
  - configmap-backend.yaml
  - configmap-frontend.yaml
  - secret.yaml
  - postgres.yaml
  - backend.yaml
  - worker.yaml
  - frontend.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - db-bootstrap-job.yaml

# Images for ArgoCD to update
images:
  - name: jayr-abawag/p2-pos-backend
    newName: ghcr.io/jayr-abawag/p2-pos-backend
    newTag: latest
  - name: jayr-abawag/p2-pos-frontend
    newName: ghcr.io/jayr-abawag/p2-pos-frontend
    newTag: latest
